fixtures:
  repositories:
    stdlib:
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
      ref: "4.15.0"
    apache:
      repo: "https://github.com/puppetlabs/puppetlabs-apache.git"
      ref: "1.11.0"
    concat:
      repo: "https://github.com/puppetlabs/puppetlabs-concat.git"
      ref: "2.2.0"
    remote_file:
      repo: "https://github.com/lwf/puppet-remote_file.git"
      ref: "v1.1.3"
  symlinks:
    flask_app: "#{source_dir}"
